### ISSUE TITLE
working with kafka

### ISSUE THREAD

**Issue by GabrielMller** [avioconsulting/mule-opentelemetry-module#114]
Hi, I'm working with Kafka on Mulesoft, and I would like to pass the trace id from the publisher to the consumer, I tried to put a traceparent header, but the trace id did not propagate, is there already a way to do this or has it not been implemented yet?

**Comment by manikmagar** [comment]
@GabrielMller As per specs, `traceparent` does include traceId. See details about traceparent [here](https://avioconsulting.github.io/mule-opentelemetry-module/#_traceparent_http_header_details). It is used by the consumer to establish parent-child relationship of the distributed traces. If the consumer side is this module, then that relationship will be established but the module does not pass or extract traceId from that traceparent. 

If you need to send traceId as a separate header then you can set it, just like traceparent. `vars.OTEL_TRACE_CONTEXT.traceId` can give you the current trace id for propagating. [Documentation](https://avioconsulting.github.io/mule-opentelemetry-module/#_context_extraction) was missing the latest screenshot but #115  should correct that gap.

I hope that answers what you are looking for.

**Comment by GabrielMller** [comment]
Ok, thanks for your help!

**Comment by JYOTHI-SHRAVZ** [comment]
Hi ,is this implemented yet ? Or is there any plans to implement it in the near future?

**Comment by manikmagar** [comment]
#223 implements support for propagating context with headers - See [src/test/resources/mule-kafka-example.xml](./src/test/resources/mule-kafka-example.xml) for publisher and consumer configuration examples.
