### ISSUE TITLE
Sub Flows

### ISSUE THREAD

**Issue by GabrielMller** [avioconsulting/mule-opentelemetry-module#130]
Hi, I'm trying to use the new version of the connector but whenever it arrives in a sub-flow it can't build the trace for the processes, I tried to disable it but the flow reference still tries to build the trace

**Comment by adesjardin** [comment]
@GabrielMller - are you able to provide a simple sample project that produces your issue and the detailed error/exception you're seeing?

**Comment by manikmagar** [comment]
@GabrielMller I am using 1.4.0 for demos and not seeing any errors with flow-ref tracing for sub-flows. Sub-flows are not really a component at runtime, so they don't get processing spans but all processors in the sub-flow get spans (per span configuration).

If you could provide some additional information that Adam requested above, that would be helpful. Thanks!

**Comment by manikmagar** [comment]
Without any examples to reproduce or more information, I am guessing this is related to #137.

**Comment by manikmagar** [comment]
Closing it along with #137. Feel free to reopen if that is not the case.
