### ISSUE TITLE
Warnings for policy components

### ISSUE THREAD

**Issue by manikmagar** [avioconsulting/mule-opentelemetry-module#188]
Policy components are not part of the standard flow and thus the module generates warnings in logs for each execution. 

![image](https://github.com/avioconsulting/mule-opentelemetry-module/assets/877286/fc25d04f-1175-4d9e-855b-2397e854ad45)

**Comment by holiday-sunrise** [comment]
when will that be fixed

**Comment by holiday-sunrise** [comment]
The Problem is now not fixed ? Policies are not supported ?
