### ISSUE TITLE
CloudHub Deployment

### ISSUE THREAD

**Issue by khpeet** [avioconsulting/mule-opentelemetry-module#39]
I was able to get my exporter working correctly locally, but deploying to CloudHub is showing a `404` error in the logs when trying to post spans to my custom exporter - is there some other config required in the example applications provided from an exporter perspective when deploying to CloudHub?

**Comment by khpeet** [comment]
Update: I was able to get my otel exporter working by specifying properties in the Cloudhub deployment. Though, I am now running into an issue where the `request-connection` in app1 doesn't make outbound calls to app2 when using `localhost` or the endpoint of the deployment in app2:

```
<http:request-connection host="localhost" port="8082" />
```

```
<http:request-connection host="mule-otel-app-2.us-e2.cloudhub.io" port="8082" />
```

```
HTTP GET on resource 'http://localhost:8082/api/app2' failed: Connection refused.
```

**Comment by manikmagar** [comment]
@khpeet the example projects are configured to run in the onprem/local runtime and use the zipkin running in local docker. Hence all local host usage. If you are deploying to CH, you would need to adjust all those urls to be accessible over CH. If you are running Zipkin in the docker, it may not be accessible to cloud hub  unless you exposed it to the internet and use appropriate URL in the exporter config.

**Comment by khpeet** [comment]
@manikmagar - right - I tried that above as an example by specifying the CH generated http endpoint for app2 within app1's request connection, and it just times out.

**Comment by manikmagar** [comment]
@khpeet you might want to change the listener ports to 8081 for CH. 8082 is reserved for HTTPS on CH.

**Comment by khpeet** [comment]
@manikmagar  - you mean like this?

app1:
```
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="79881531-bfaa-49fd-8227-b67e35d64cf8" basePath="/api">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
...
<http:request-connection host="mule-otel-app-2.us-e2.cloudhub.io" port="8082" />
```

app2: 
```
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="79881531-bfaa-49fd-8227-b67e35d64cf8" basePath="/api">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
```

**Comment by khpeet** [comment]
Hmm.. unfortuntately still connection timeout with those updates:

```
HTTP GET on resource 'http://mule-otel-app-2.us-e2.cloudhub.io:8081/api/app2' failed: Connect timeout.
```

Appreciate the feedback, I'll try to play around with it some more

**Comment by manikmagar** [comment]
@khpeet I was at MuleSoft CONNECT conference and was trying to answer through phone :).  sorry, I didn't see it through. 

The Cloudhub shared listener's listen on standard HTTP(/s) port 80(/443). It internally routes to corresponding ports 8081(/8082). 


If you make following changes, it should work - 

app1: - HTTP Listener on 8081

```
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="79881531-bfaa-49fd-8227-b67e35d64cf8" basePath="/api">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
```

**The connection port should be 80 for http.** This should resolve your timeout issue (assuming you are not deploying into VPC).

```
<http:request-connection host="mule-otel-app-2.us-e2.cloudhub.io" port="80" />
```

app2: - HTTP Listener port on 8081

```
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="79881531-bfaa-49fd-8227-b67e35d64cf8" basePath="/api">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>

```

Hope that helps!

**Comment by manikmagar** [comment]
Presuming that original question is resolved. Closing this issue.
