### ISSUE TITLE
No traces for Anypoint Flows

### ISSUE THREAD

**Issue by lorenzoash** [avioconsulting/mule-opentelemetry-module#64]
I have created multiple applications using HTTP Listener and HTTP Request to generate Spans and traces.

When using the CTG connector to implement an API I am not able to retrieve traces or spans while using the open telemetry dependency. Even attempted to turn on "spanAllProcessors"  and still no traces. 

We are sending this data into Splunk APM as well. 

**Flow using HTTP Listener (working)**
![image](https://user-images.githubusercontent.com/31445416/195692206-ee96aaf5-35a9-45a0-b852-9ab780852719.png)

**Flow using CTG Connector (not working)**
![image](https://user-images.githubusercontent.com/31445416/195692309-3c728320-2322-46f0-ac22-a4b47b4585a4.png)

**Comment by manikmagar** [comment]
Hi @lorenzoash 

Which runtime version and deployment environment (ch/onprem..) are you using? 

> I have created multiple applications using HTTP Listener and HTTP Request to generate Spans and traces.

Good to hear this. I presume all these spans and traces are appearing in APM as expected.

> When using the CTG connector to implement an API I am not able to retrieve traces or spans while using the open telemetry dependency. Even attempted to turn on "spanAllProcessors" and still no traces.

Is this a different app? When you say no traces, is that for CTG connector span OR in general not a single span is making out of that CTG application? 

Could you share the opentelemetry configuration from that CTG application? Also, Are there any errors in the log? 

Btw few hours ago, we released a [1.1.0](https://github.com/avioconsulting/mule-opentelemetry-module/releases/tag/v1.1.0) version of this module. You could try using that and see if anything changes.

**Comment by lorenzoash** [comment]
We were able to fix the issue. The code was never deployed.... lol OUR BAD!!  BUT THANK YOU FOR THE QUICK RESPONSE

**Comment by manikmagar** [comment]
np, thank you for the update. I will close this issue then.
