### ISSUE TITLE
DbComponent Error

### ISSUE THREAD

**Issue by smulepatel** [avioconsulting/mule-opentelemetry-module#65]
Line 51 of https://github.com/avioconsulting/mule-opentelemetry-module/blob/331ad8ef933c9acd5a8f70f19996035f8522193a/src/main/java/com/avioconsulting/mule/opentelemetry/internal/processor/DBProcessorComponent.java seems to be throwing null pointer exception
![image](https://user-images.githubusercontent.com/41742705/195755997-9d3afee9-f164-46d2-99ab-d7ee97b1d835.png)

 - Error in handling processor start event
java.lang.NullPointerException: null
	at com.avioconsulting.mule.opentelemetry.internal.processor.DBProcessorComponent.getAttributes(DBProcessorComponent.java:51) ~[?:?]
	at com.avioconsulting.mule.opentelemetry.internal.processor.AbstractProcessorComponent.getStartTraceComponent(AbstractProcessorComponent.java:140) ~[?:?]
	at com.avioconsulting.mule.opentelemetry.internal.processor.MuleNotificationProcessor.lambda$handleProcessorStartEvent$0(MuleNotificationProcessor.java:97) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_202]

**Comment by manikmagar** [comment]
@smulepatel Could you please share the DB connector configuration element?

**Comment by smulepatel** [comment]
We have DB Config in a domain project referencing to a spring bean "OracleFacetsDataSource" in following snipped

`	<db:config name="Oracle_Facets_Configuration" doc:name="Oracle_Facets_Configuration" doc:id="f95a3738-ba5c-49e8-8608-1a695b76515c" >
		<db:data-source-connection dataSourceRef="OracleFacetsDataSource" >
			<reconnection >
				<reconnect frequency="${oracle.db.facets.reconnection.frequency}" count="${oracle.db.facets.reconnection.attempts}" />
			</reconnection>
			<db:pooling-profile maxPoolSize="${oracle.db.facets.connection.pooling.maxsize}" minPoolSize="${oracle.db.facets.connection.pooling.minsize}" acquireIncrement="${oracle.db.facets.connection.pooling.increment}" preparedStatementCacheSize="${oracle.db.facets.connection.pooling.cachesize}" maxWait="${oracle.db.facets.connection.pooling.maxwait}" maxWaitUnit="MILLISECONDS"/>
		<db:column-types >
				<db:column-type id="-10" typeName="CURSOR" />
			</db:column-types> 
		</db:data-source-connection>
	</db:config>


Spring Bean XML has 
`    <bean id="OracleFacetsDataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource" destroy-method="close">
        <property name="jdbcUrl" value="jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=${oracle.db.facets.host})(PORT=${oracle.db.facets.port}))(CONNECT_DATA=(SERVICE_NAME=${oracle.db.facets.service})))" />
        <property name="driverClass" value="oracle.jdbc.driver.OracleDriver" />
        <property name="testConnectionOnCheckin" value="${oracle.db.facets.testConnectionCheckin}" />
        <property name="idleConnectionTestPeriod" value="${oracle.db.facets.idleConnectionTestPeriod}" />
        <property name="user" value="${secure::oracle.db.facets.user}" />
        <property name="password" value="${secure::oracle.db.facets.password}" />
    </bean>`
`

**Comment by manikmagar** [comment]
@smulepatel Thank you for additional details. Issue seems to be related to config in domain instead of same mule app. Will need to look into this.

**Comment by manikmagar** [comment]
@smulepatel new version 1.2.0 of the module is released and contains fix to prevent this failure.
